### ISSUE TITLE
Double Quotes

### ISSUE THREAD

**Issue by OpenSZN39** [OpenSZN39/kraken-good-accessibility#1]
@thatkidmadrid

Christian, I keep getting an error for double quotes on line 27. I'm not sure what it is asking me to do? in terms of comparison to the screenshot I think I'm pretty much done, just want to finish these final details.

![image](https://user-images.githubusercontent.com/77280572/136454490-449a09e2-4a2d-4752-9e05-1e1700cf5b42.png)

Thanks

**Comment by OpenSZN39** [comment]
Nevermind I figured that out

**Comment by thatkidmadrid** [comment]
`role=presentation` needs to be `role="presentation"`

**Comment by thatkidmadrid** [comment]
Also there's still a lot of work that needs to be done to the structure of the page. It may look close to the reference, but the point of the exercise is to use the proper semantic tags, and use them well. Please see[ the cheatsheet ](https://learn-the-web.algonquindesign.ca/topics/html-semantics-cheat-sheet/)for a refresher of what these tags do.

You also did not test your page with Voiceover, I can tell because if you did, you would have caught a few items. I used Voiceover and it revealed some hints that you might have plagiarized  some code from someone else and I was clear in the beginning of the semester that I can tell and that I don't want to have to go through this with the program heads for an activity worth 2.7%

You're missing some important descriptions, please review the [cheatsheets for week-04](https://learn-the-web.algonquindesign.ca/courses/web-design-2/week-04/)
